# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package libsvm;
use base qw(Exporter);
use base qw(DynaLoader);
package libsvmc;
bootstrap libsvm;
package libsvm;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package libsvm;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package libsvm;

*new_param = *libsvmc::new_param;
*destroy_param = *libsvmc::destroy_param;
*set_weight = *libsvmc::set_weight;
*set_svm_type = *libsvmc::set_svm_type;
*set_kernel_type = *libsvmc::set_kernel_type;
*set_degree = *libsvmc::set_degree;
*set_gamma = *libsvmc::set_gamma;
*set_coef0 = *libsvmc::set_coef0;
*set_C = *libsvmc::set_C;
*set_nu = *libsvmc::set_nu;
*set_epsilon = *libsvmc::set_epsilon;
*new_problem = *libsvmc::new_problem;
*destroy_problem = *libsvmc::destroy_problem;
*new_problem_set = *libsvmc::new_problem_set;
*do_cross_validation = *libsvmc::do_cross_validation;
*destroy_problem_set = *libsvmc::destroy_problem_set;
*new_dataset = *libsvmc::new_dataset;
*destroy_dataset = *libsvmc::destroy_dataset;
*set_attribute = *libsvmc::set_attribute;
*predict = *libsvmc::predict;
*load_model = *libsvmc::load_model;
*destroy_model = *libsvmc::destroy_model;
*save_model_file = *libsvmc::save_model_file;
*add_dataset = *libsvmc::add_dataset;
*train = *libsvmc::train;

# ------- VARIABLE STUBS --------

package libsvm;

1;
